### PR TITLE
Migration to overte

### PR DESCRIPTION
**Pull request by AleziaKurdis**
This PR update all the url required to use the more.overte.org subdomain to get the scripts for execution.
and point to the overte-org/community-apps repository for the contribution information. 

It also add an "odometer" tool to the available applications.

### CODE REVIEW

**Comment by AleziaKurdis** [comment]
Once merged to master, 
you will have to copy the content of this repository in the subdomain more.overte.org

**Review by JulianGro — CHANGES_REQUESTED** [review]
Can you move the odometer application to a separate PR?
I can review the URL and description changes, but I cannot review a new JavaScript app.

**Comment by AleziaKurdis** [comment]
You will notice some entire scripts appear as different. This is because the original was committed with "CR LF" instead of our standard "LF" line break symbol.

For the odometer, it's not going to have impacts. This is very standard application code, and fully isolated. 
You can try it by running this: https://aleziakurdis.github.io/odometer/odometer.js
I would prefer not have to cut that from that PR just for that. Maybe you can make it reviews by someone else.
(I'm using it for a few month by the way.)
Let me know.

**Review by JulianGro — APPROVED** [review]
I guess, looking at it it seems simple enough.

**Pull request merged**
