### PR TITLE
Update app-survivalKit.js for V8

### PR DESCRIPTION
**Pull request by ksuprynowicz**
I haven't tested it but should hopefully fix the issue

### CODE REVIEW

**Review by JulianGro — APPROVED** [review]

**Comment by AleziaKurdis** [comment]
Why doing this? It is already there.
image

**Comment by AleziaKurdis** [comment]
Why this one? it's already declared:
image

**Comment by AleziaKurdis** [comment]
The "eventObj" bug is probably present in many app including.
it was probably from an old template i reused many time.

**Comment by AleziaKurdis** [comment]
These 2 other apps will have the same issue (eventObj):
- **community-apps-master\applications\notes\app-notes.js**
- **community-apps-master\applications\materialDataCreator\appMaterialDataCreator.js**

This one too , same pattern but the variable is called "eventzget" 
- **community-apps-master\applications\domain-navigator\dom_nav.js**

**Comment by AleziaKurdis** [comment]
At least the new template I published recently doesn't have the issues.

**Comment by AleziaKurdis** [comment]
I just did the PR #24 that solves the 4 app in problem.
So it include the fix for survival kit

Please close this PR #23 since it's incorrect and will be fix by the PR #24.

**Pull request closed without merging**
