### PR TITLE
Add the "Light Bulb Generator" app

### PR DESCRIPTION
**Pull request by AleziaKurdis**
This PR adds the "Light Bulb Generator" application:
To generate rapidly a visible glowing light source with its light beam.

image

image

### CODE REVIEW

**Review by ksuprynowicz — APPROVED** [review]
Thank you!
Everything looks fine :)

**Comment by AleziaKurdis** [comment]
This application is generating an entity that is running a client entity script to generate the light and material as local entities. 
This script (lightBulb.js) will be located in this application repository.
This means that everywhere that such a light build will be used, every single visitor will run it. The script will be then read from the community-app web server at least one time to be kept in cache.
This is the first problem. Are we ok to support this load? (Maybe at short or medium term)

The second problem is that it will induce a dependency to the community-app web server for the content that are using this.
Is this ok ? I'm not sure it is.

**Comment by ksuprynowicz** [comment]
I'd say that such dependency is perfectly fine. I also tested the script right now and it works like it should
overte-snap-by-X74hc595-on-2022-07-16_19-41-52
:

**Comment by JulianGro** [comment]
If I remember correctly how this works, you need to regenerate that metdata.js. After that I would merge it.

**Pull request merged**
