### PR TITLE
Add Body Paint app

### PR DESCRIPTION
**Pull request by SilverfishVR**
also testing if line breaks are allowed in app description

### CODE REVIEW

**Comment by SilverfishVR** [comment]
ups, nevermind, turns out that line breaks in the description should be in HTML `<br>` and not string `\n`

**Comment by SilverfishVR** [comment]
Changes made:
- Polylines created renamed to "bodypaint" from "fingerpaint".
- App icon modified and moved to script directory (from resource file).
- Fixed continuous line mode (sort of).
- Increased max line width to 0.05 (was 0.036).
- Some dead code removed.
- 2 brushes added, "Paws" (https://freesvg.org/1553022565) and "keepOut" (https://freesvg.org/muga-barb-wire) both are licensed under https://creativecommons.org/licenses/publicdomain/
- Renamed to Bodypaint4 since it was previously distributed as Bodypaint3.

Known issues:
- "Continuous line mode" is not, it just starts a new line every 52 segments, apparently due the the issue with polylines sometimes disappearing.
- If using "Continuous line mode" and "Trigger sensitive width" in desktop, the first segment on subsequent lines is too big, can't figure out why.

**Review by ksuprynowicz — APPROVED** [review]
Everything looks fine to me. Some of the code is commented out, and normally should be removed but I suggest keeping it as comments for now because it might have had some purpose that is not obvious right now.

**Comment by ksuprynowicz** [comment]
Like we discussed at last meeting I reviewed only recent changes to the app.

**Pull request merged**
